#!/usr/bin/env bash
# dnsmasq for LAN_HOSTNAME / LOCAL_HOSTNAME.
set -euo pipefail
INIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${INIT_DIR}/lib.sh"
parse_task_args "$@"
begin_task "08 · Network DNS for ${LAN_HOSTNAME}"

if [[ "${SKIP_DNS}" == "true" ]]; then
  warn "Skipping LAN DNS setup (SKIP_DNS=true)"
  exit 0
fi

ensure_path_has_brew
require_cmd brew
require_cmd route
require_cmd ipconfig

primary_if="$(route -n get default 2>/dev/null | awk '/interface:/{print $2; exit}')"
[[ -n "${primary_if}" ]] || fail "Could not determine primary network interface"
mac_ip="$(ipconfig getifaddr "${primary_if}" 2>/dev/null || true)"
[[ -n "${mac_ip}" ]] || fail "No IP on ${primary_if}. Connect to LAN/Wi-Fi and re-run."

brew_prefix="$(brew --prefix)"
conf_file="${brew_prefix}/etc/dnsmasq.conf"
resolver_file="/etc/resolver/clinic"

already=false
if [[ -f "${conf_file}" ]] \
  && grep -Fq "address=/${LAN_HOSTNAME}/${mac_ip}" "${conf_file}" \
  && [[ -f "${resolver_file}" ]]; then
  already=true
fi

if [[ "${already}" == true && "${FORCE}" != true ]]; then
  skip "dnsmasq already maps ${LAN_HOSTNAME} → ${mac_ip}"
  dim "${conf_file}"
  exit 0
fi

info "Primary interface: ${primary_if} · IP: ${mac_ip}"
warn "Static IP is NOT automated — reserve ${mac_ip} in the router / System Settings"

brew list --formula dnsmasq >/dev/null 2>&1 || brew install dnsmasq >/dev/null
mkdir -p "${brew_prefix}/etc"

cat > "${conf_file}" <<EOF
# Generated by bahmni-local/initialize/08-dns.sh
# Local authoritative DNS for ${LAN_HOSTNAME} -> ${mac_ip}

listen-address=127.0.0.1,${mac_ip}
port=53
bind-interfaces

no-resolv
server=${UPSTREAM_DNS_1}
server=${UPSTREAM_DNS_2}

address=/${LAN_HOSTNAME}/${mac_ip}
address=/${LOCAL_HOSTNAME}/${mac_ip}

cache-size=1000
EOF
ok "Wrote ${conf_file}"

info "Installing split-DNS resolver (sudo)…"
sudo mkdir -p /etc/resolver
sudo tee "${resolver_file}" >/dev/null <<EOF
# Generated by bahmni-local/initialize/08-dns.sh
nameserver 127.0.0.1
EOF
ok "Wrote ${resolver_file}"

info "Restarting dnsmasq…"
brew services restart dnsmasq >/dev/null

if command -v dig >/dev/null 2>&1; then
  dim "${LAN_HOSTNAME} => $(dig +short "${LAN_HOSTNAME}" @127.0.0.1 | tr '\n' ' ')"
fi
if sudo lsof -nP -iUDP:53 2>/dev/null | grep -q dnsmasq; then
  ok "dnsmasq is listening on UDP/53"
else
  warn "dnsmasq may not be bound to UDP/53 — check: brew services list"
fi
dim "LAN clients should use DNS server ${mac_ip}"
