#!/usr/bin/env bash
set -euo pipefail

# -----------------------------
# Config you may change
# -----------------------------
DOMAIN_FQDN="bahmni.clinic"
UPSTREAM_DNS_1="1.1.1.1"
UPSTREAM_DNS_2="8.8.8.8"

# If you want dnsmasq to listen only on Wi-Fi, set this to "true".
WIFI_ONLY="false"

# -----------------------------
# Helpers
# -----------------------------
log() { printf "\n==> %s\n" "$*"; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing required command: $1"; exit 1; }
}

get_homebrew_prefix() {
  if command -v brew >/dev/null 2>&1; then
    brew --prefix
  else
    echo ""
  fi
}

get_primary_interface() {
  # Finds the interface used for the default route.
  route -n get default 2>/dev/null | awk '/interface:/{print $2; exit}'
}

get_ip_for_interface() {
  local ifname="$1"
  ipconfig getifaddr "$ifname" 2>/dev/null || true
}

ensure_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew not found. Install Homebrew first: https://brew.sh/"
    exit 1
  fi
}

ensure_root_for_privileged_steps() {
  # Some steps (creating /etc/resolver) require sudo.
  if [[ "${EUID}" -ne 0 ]]; then
    return 0
  fi
}

# -----------------------------
# Main
# -----------------------------
ensure_brew
require_cmd awk
require_cmd route
require_cmd ipconfig
require_cmd mkdir
require_cmd tee

BREW_PREFIX="$(get_homebrew_prefix)"
DNSMASQ_BIN="${BREW_PREFIX}/sbin/dnsmasq"
CONF_DIR="${BREW_PREFIX}/etc"
CONF_FILE="${CONF_DIR}/dnsmasq.conf"
RESOLVER_DIR="/etc/resolver"
RESOLVER_FILE="${RESOLVER_DIR}/clinic"

log "Detecting primary interface + IP…"
PRIMARY_IF="$(get_primary_interface)"
if [[ -z "${PRIMARY_IF}" ]]; then
  echo "Could not determine primary interface."
  exit 1
fi

MAC_IP="$(get_ip_for_interface "${PRIMARY_IF}")"
if [[ -z "${MAC_IP}" ]]; then
  echo "Could not determine IP for interface: ${PRIMARY_IF}"
  echo "Are you connected to Wi-Fi / LAN?"
  exit 1
fi

log "Primary interface: ${PRIMARY_IF}"
log "Mac IP on that interface: ${MAC_IP}"

log "Installing dnsmasq…"
brew install dnsmasq >/dev/null

if [[ ! -x "${DNSMASQ_BIN}" ]]; then
  echo "dnsmasq binary not found at ${DNSMASQ_BIN}"
  echo "Try: brew info dnsmasq"
  exit 1
fi

log "Creating dnsmasq config at: ${CONF_FILE}"
mkdir -p "${CONF_DIR}"

# Build listen-address based on WIFI_ONLY
LISTEN_ADDR="listen-address=127.0.0.1,${MAC_IP}"
if [[ "${WIFI_ONLY}" == "true" ]]; then
  # Still safe because we bind to the chosen interface IP + localhost only.
  LISTEN_ADDR="listen-address=127.0.0.1,${MAC_IP}"
fi

cat > "${CONF_FILE}" <<EOF
# Generated by setup-bahmni-dns.sh
# Local authoritative DNS for ${DOMAIN_FQDN} -> ${MAC_IP}
# Forwards everything else to upstream resolvers.

${LISTEN_ADDR}
port=53
bind-interfaces

no-resolv
server=${UPSTREAM_DNS_1}
server=${UPSTREAM_DNS_2}

# Local record:
address=/${DOMAIN_FQDN}/${MAC_IP}

# Optional: cache size (tune as desired)
cache-size=1000
EOF

log "Setting up split-DNS on THIS Mac for *.clinic via /etc/resolver/clinic"
log "This ensures this Mac also resolves bahmni.clinic using local dnsmasq."

# Needs sudo to write /etc/resolver
sudo mkdir -p "${RESOLVER_DIR}"
sudo tee "${RESOLVER_FILE}" >/dev/null <<EOF
# Generated by setup-bahmni-dns.sh
# Send all *.clinic queries to local dnsmasq on this Mac.
nameserver 127.0.0.1
EOF

log "Starting dnsmasq as a background service…"
brew services restart dnsmasq >/dev/null

log "Verifying dnsmasq is listening on port 53…"
if sudo lsof -nP -iUDP:53 | grep -q dnsmasq; then
  echo "dnsmasq is listening on UDP/53 ✅"
else
  echo "dnsmasq does not appear to be listening on UDP/53."
  echo "Check logs: brew services list && log show --predicate 'process == \"dnsmasq\"' --last 5m"
  exit 1
fi

log "Testing DNS resolution locally…"
require_cmd dig

echo
echo "Test 1 (local authoritative):"
dig +short "${DOMAIN_FQDN}" @127.0.0.1 || true

echo
echo "Test 2 (forwarding public DNS):"
dig +short google.com @127.0.0.1 || true

echo
echo "DONE ✅"
echo
echo "Next (outside scripts):"
echo "1) Ensure this Mac keeps IP stable (router DHCP reservation or manual IP)."
echo "2) On each client device, set DNS server to: ${MAC_IP}"
echo "   Then test from that device:"
echo "     nslookup ${DOMAIN_FQDN} ${MAC_IP}"
echo "     or open: http://${DOMAIN_FQDN}  (or https if you have TLS)"
