KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret-password"
    user_admin="admin-secret-password"
    user_mirrormaker="mirrormaker-secret-password";
};

