#!/usr/bin/env bash
# Task 080 parks odoo-connect's feed markers with SQL that must fit the table
# odoo-connect 1.0.0 (Odoo 16) actually creates: id / feed_uri /
# last_read_entry_id / feed_uri_for_last_read_entry and NOTHING else. The Odoo 10
# era table also carried create_date/write_date, and SQL written against it
# stops an install (column "write_date" does not exist).
# The three shared columns are the whole contract; they fit both shapes.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fails=0
ok_(){ printf '  ok   %s\n' "$1"; }
bad(){ printf '  FAIL %s\n' "$1"; fails=$((fails+1)); }
T80="${HERE}/../tasks/080-stack.sh"
sql="$(sed -n "/<<'SQL'/,/^SQL\$/p" "$T80" | sed '1d;$d')"
[ -n "$sql" ] && ok_ "080 carries its marker SQL in a SQL heredoc" || bad "no SQL heredoc found in 080"
printf '%s' "$sql" | grep -qE 'write_date|create_date' && bad "marker SQL names create_date/write_date, which the Odoo 16 table lacks" || ok_ "marker SQL names only the three shared columns"

# Live proof against a real PostgreSQL when one is at hand (the dev box's
# Homebrew instance); a host without psql still gets the static guard above.
db="${MARKERS_TEST_DB:-bahmni_test}"
if command -v psql >/dev/null 2>&1 && psql -d "$db" -qAt -c 'select 1' >/dev/null 2>&1; then
  sch="mk_test_$$"
  run(){ psql -d "$db" -v ON_ERROR_STOP=1 -q -At -v f="$1" -v e="$2" -v p="$3"; }
  # the seed's own DDL (pg_dump of the hub's odoo database)
  psql -d "$db" -q -v ON_ERROR_STOP=1 >/dev/null <<DDL
CREATE SCHEMA ${sch};
CREATE TABLE ${sch}.markers (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, feed_uri_for_last_read_entry varchar(250) NOT NULL, feed_uri varchar(250) NOT NULL, last_read_entry_id varchar(250) NOT NULL);
INSERT INTO ${sch}.markers (feed_uri_for_last_read_entry, feed_uri, last_read_entry_id) VALUES ('old-page','http://openmrs:8080/openmrs/ws/atomfeed/drug/recent','old-entry');
DDL
  body="SET search_path=${sch};
${sql}"
  printf '%s\n' "$body" | run 'http://openmrs:8080/openmrs/ws/atomfeed/drug/recent' 'tag:new-drug' 'http://openmrs:8080/openmrs/ws/atomfeed/drug/599' >/dev/null 2>"/tmp/mk.$$" && ok_ "updates an existing row on the Odoo 16 table" || bad "update failed: $(cat /tmp/mk.$$)"
  printf '%s\n' "$body" | run 'http://openmrs:8080/openmrs/ws/atomfeed/saleable/recent' 'tag:new-sale' 'http://openmrs:8080/openmrs/ws/atomfeed/saleable/7' >/dev/null 2>"/tmp/mk.$$" && ok_ "inserts a missing row on the Odoo 16 table" || bad "insert failed: $(cat /tmp/mk.$$)"
  got="$(psql -d "$db" -qAt -c "select feed_uri||'='||last_read_entry_id from ${sch}.markers order by 1" | tr '\n' ' ')"
  [ "$got" = "http://openmrs:8080/openmrs/ws/atomfeed/drug/recent=tag:new-drug http://openmrs:8080/openmrs/ws/atomfeed/saleable/recent=tag:new-sale " ] && ok_ "exactly one row per feed, at the new position" || bad "rows are: $got"
  psql -d "$db" -q -c "DROP SCHEMA ${sch} CASCADE" >/dev/null 2>&1; rm -f "/tmp/mk.$$"
else
  ok_ "live PostgreSQL proof skipped (no psql / no ${db})"
fi
exit "$fails"
