#!/usr/bin/env bash
# The seed-shape rules the seed sitting applies before a database is touched:
# the dumps come from the pinned OpenMRS and Odoo versions, and the hub had
# partitioned its address and customer-attribute ids before it was dumped.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
CLINIC_DIR="$TMP"; . "${HERE}/../lib.sh"; . "${HERE}/../state.sh"
fails=0
assert_contains(){ if printf '%s' "$2" | grep -q -- "$3"; then printf '  ok   %s\n' "$1"; else printf '  FAIL %s: output lacks %q\n' "$1" "$3"; fails=$((fails+1)); fi; }
assert_rc(){ if [ "$2" -eq "$3" ]; then printf '  ok   %s\n' "$1"; else printf '  FAIL %s: rc %s want %s\n' "$1" "$2" "$3"; fails=$((fails+1)); fi; }
OPENMRS_IMAGE_NAME=infoiplitin/openmrs:iplit-1.2.0-1200-03
# address_seq_block TABLE SEQ FORM STEP : a CREATE TABLE plus its id sequence,
# in either pg_dump shape (FORM=create: CREATE SEQUENCE; FORM=identity: the
# multi-line GENERATED ... AS IDENTITY form) -- both are real pg_dump output
# for a serial column, depending on whether Odoo's schema used `serial` or an
# identity column, and the address-table gate must recognise both.
address_seq_block(){ # TABLE SEQ FORM STEP
  local tbl="$1" seq="$2" form="$3" step="$4"
  if [ "$form" = identity ]; then
    cat <<SQL
CREATE TABLE public.$tbl (
    id integer NOT NULL
);
ALTER TABLE ONLY public.$tbl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.$seq
    START WITH 1
    INCREMENT BY $step
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
SQL
  else
    cat <<SQL
CREATE TABLE public.$tbl (
    id integer NOT NULL
);
CREATE SEQUENCE public.$seq
    START WITH 1
    INCREMENT BY $step
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
SQL
  fi
}
# seed-shape gate: a 662-4 / Odoo 10 seed is refused (old openmrs, old odoo)
mkdir -p "$TMP/seed-old"
printf 'CREATE TABLE person (x int);\n' | gzip > "$TMP/seed-old/openmrs.sql.gz"
printf 'CREATE TABLE product_uom (x int);\n' | gzip > "$TMP/seed-old/odoo.sql.gz"
printf 'x\n' | gzip > "$TMP/seed-old/openelis.sql.gz"
out="$(seed_shape_verdict "$TMP/seed-old" 2>&1)"; rc=$?
assert_rc "old openmrs dump refused (rc)" "$rc" 1
assert_contains "old openmrs dump refused" "$out" "seed openmrs.sql.gz is not an iplit-1.2.0 dump (changeset 20251223-drop-default-value-from-column absent)"

# openmrs is 1.2.0 but odoo is still Odoo 10 -- refused for the odoo reason specifically
mkdir -p "$TMP/seed-mixed"
printf "INSERT INTO liquibasechangelog VALUES ('20251223-drop-default-value-from-column','iplit');\n" | gzip > "$TMP/seed-mixed/openmrs.sql.gz"
printf 'CREATE TABLE product_uom (x int);\n' | gzip > "$TMP/seed-mixed/odoo.sql.gz"
printf 'x\n' | gzip > "$TMP/seed-mixed/openelis.sql.gz"
out="$(seed_shape_verdict "$TMP/seed-mixed" 2>&1)"; rc=$?
assert_rc "old odoo dump refused (rc)" "$rc" 1
assert_contains "old odoo dump refused" "$out" "seed odoo.sql.gz is not an Odoo 16 dump (no uom_uom)"

# a 1.2.0 / Odoo 16 seed passes the gate
mkdir -p "$TMP/seed-new"
printf "INSERT INTO liquibasechangelog VALUES ('20251223-drop-default-value-from-column','iplit');\n" | gzip > "$TMP/seed-new/openmrs.sql.gz"
{ printf 'CREATE TABLE uom_uom (x int);\n'; address_seq_block village_village village_village_id_seq create 10; address_seq_block res_partner_attributes res_partner_attributes_id_seq create 10; } | gzip > "$TMP/seed-new/odoo.sql.gz"
printf 'x\n' | gzip > "$TMP/seed-new/openelis.sql.gz"
out="$(seed_shape_verdict "$TMP/seed-new" 2>&1)"; rc=$?
assert_rc "new seed passes the version gate (rc)" "$rc" 0
assert_contains "new seed passes the version gate" "$out" "seed shape: openmrs iplit-1.2.0, odoo 16"

# pipefail proof: the changeset line is the FIRST line of a large multi-line dump, so
# grep -m1 matches and closes its read end before gzip finishes writing -- gzip is
# killed by SIGPIPE (exit 141) while still mid-write. Under `set -o pipefail` that
# would poison a bare `gzip -dc f | grep -qm1 pat` pipeline's status to 141 even
# though grep found its match; the gate wraps gzip in `{ ... || true; }` precisely so
# this large-dump case still passes.
mkdir -p "$TMP/seed-big"
{ printf "INSERT INTO liquibasechangelog VALUES ('20251223-drop-default-value-from-column','iplit');\n"; seq 1 50000 | awk '{print "INSERT INTO filler VALUES (" $1 ");"}'; } | gzip > "$TMP/seed-big/openmrs.sql.gz"
{ printf 'CREATE TABLE uom_uom (x int);\n'; address_seq_block village_village village_village_id_seq create 10; address_seq_block res_partner_attributes res_partner_attributes_id_seq create 10; } | gzip > "$TMP/seed-big/odoo.sql.gz"
printf 'x\n' | gzip > "$TMP/seed-big/openelis.sql.gz"
out="$(seed_shape_verdict "$TMP/seed-big" 2>&1)"; rc=$?
assert_rc "large multi-line seed passes despite early pipe close (rc)" "$rc" 0
assert_contains "large multi-line seed passes despite early pipe close" "$out" "seed shape: openmrs iplit-1.2.0, odoo 16"

# address-table seed gate: a seed dumped before the hub strode village_village and
# res_partner_attributes must be refused -- it would hand a fresh clinic ids
# the hub already uses. Every fixture below is otherwise 1.2.0/Odoo-16
# shaped so it clears the earlier gates and reaches this one.
mk_address_seed(){ # DIR VILLAGE_FORM VILLAGE_STEP ATTRS_FORM ATTRS_STEP [no-village]
  local dir="$1" vform="$2" vstep="$3" aform="$4" astep="$5" novillage="${6:-}"
  mkdir -p "$dir"
  printf "INSERT INTO liquibasechangelog VALUES ('20251223-drop-default-value-from-column','iplit');\n" | gzip > "$dir/openmrs.sql.gz"
  if [ "$novillage" = no-village ]; then
    { printf 'CREATE TABLE uom_uom (x int);\n'; address_seq_block res_partner_attributes res_partner_attributes_id_seq "$aform" "$astep"; } | gzip > "$dir/odoo.sql.gz"
  else
    { printf 'CREATE TABLE uom_uom (x int);\n'; address_seq_block village_village village_village_id_seq "$vform" "$vstep"; address_seq_block res_partner_attributes res_partner_attributes_id_seq "$aform" "$astep"; } | gzip > "$dir/odoo.sql.gz"
  fi
  printf 'x\n' | gzip > "$dir/openelis.sql.gz"
}

# step 1, CREATE SEQUENCE form -- refused
mk_address_seed "$TMP/seed-address-create-step1" create 1 create 10
out="$(seed_shape_verdict "$TMP/seed-address-create-step1" 2>&1)"; rc=$?
assert_rc "village_village step 1 (CREATE SEQUENCE form) refused (rc)" "$rc" 1
assert_contains "village_village step 1 (CREATE SEQUENCE form) names the partitioned ids" "$out" "partitioned"
assert_contains "village_village step 1 (CREATE SEQUENCE form) names a fresh seed" "$out" "fresh seed"

# step 1, IDENTITY multi-line form -- refused
mk_address_seed "$TMP/seed-address-identity-step1" identity 1 create 10
out="$(seed_shape_verdict "$TMP/seed-address-identity-step1" 2>&1)"; rc=$?
assert_rc "village_village step 1 (IDENTITY form) refused (rc)" "$rc" 1
assert_contains "village_village step 1 (IDENTITY form) names the partitioned ids" "$out" "partitioned"
assert_contains "village_village step 1 (IDENTITY form) names a fresh seed" "$out" "fresh seed"

# step 10 in each form -- accepted (both tables, both forms, to prove the gate
# reads BOTH shapes as a pass, not just as a refusal-trigger)
mk_address_seed "$TMP/seed-address-step10-create" create 10 create 10
out="$(seed_shape_verdict "$TMP/seed-address-step10-create" 2>&1)"; rc=$?
assert_rc "step 10, CREATE SEQUENCE form, accepted (rc)" "$rc" 0
mk_address_seed "$TMP/seed-address-step10-identity" identity 10 identity 10
out="$(seed_shape_verdict "$TMP/seed-address-step10-identity" 2>&1)"; rc=$?
assert_rc "step 10, IDENTITY form, accepted (rc)" "$rc" 0

# table absent entirely -- refused as a wrong-shape seed, not a step-1 refusal
mk_address_seed "$TMP/seed-address-no-village" create 10 create 10 no-village
out="$(seed_shape_verdict "$TMP/seed-address-no-village" 2>&1)"; rc=$?
assert_rc "no village_village table refused (rc)" "$rc" 1
assert_contains "no village_village table names the missing table" "$out" "village_village"
assert_contains "no village_village table names the partitioned ids" "$out" "partitioned"

# attributes sequence unstrided while village_village is fine -- refused,
# naming the attributes sequence specifically
mk_address_seed "$TMP/seed-address-attrs-unstrided" create 10 create 1
out="$(seed_shape_verdict "$TMP/seed-address-attrs-unstrided" 2>&1)"; rc=$?
assert_rc "res_partner_attributes step 1 refused (rc)" "$rc" 1
assert_contains "res_partner_attributes step 1 names the sequence" "$out" "res_partner_attributes_id_seq"
assert_contains "res_partner_attributes step 1 names the partitioned ids" "$out" "partitioned"
assert_contains "res_partner_attributes step 1 names a fresh seed" "$out" "fresh seed"

exit "$fails"
